# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 编码

name: "encoder"
backend: "onnxruntime"
default_model_filename: "encoder.onnx"

max_batch_size: 64
input [
 {
    name: "chunk"
    data_type: TYPE_FP32
    dims: [1, 0, 80]
  },
  {
    name: "offset"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "required_cache_size"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "att_cache"
    data_type: TYPE_FP32
    dims: [12, 4, 0, 128]
  },
  {
    name: "cnn_cache"
    data_type: TYPE_FP32
    dims: [12, 1, 256, 7]
  },
  {
    name: "att_mask"
    data_type: TYPE_BOOL
    dims: [1, 1, 0]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [0, 0, 256]
  },
  {
    name: "r_att_cache"
    data_type: TYPE_FP32
    dims: [12, 4, 0, 128]
  },
  {
    name: "r_cnn_cache"
    data_type: TYPE_FP32
    dims: [12, 1, 256, 0]
  }
]

dynamic_batching {
    preferred_batch_size: [ 16, 32 ]
  }


instance_group [
    {
      count: 2
      kind: KIND_CPU
    }
]

