# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# # 解码器

name: "decoder"
backend: "onnxruntime"
default_model_filename: "decoder.onnx"

max_batch_size: 640
input [
  {
    name: "hyps"
    data_type: TYPE_INT64
    format: FORMAT_NONE
    dims: [ 0, 0 ]
  },
  {
    name: "hyps_lens"
    data_type: TYPE_INT64
    format: FORMAT_NONE
    dims: [ 0 ]
  },
  {
    name: "encoder_out"
    data_type: TYPE_FP32
    format: FORMAT_NONE
    dims: [ 1, 0, 256 ]
  }
]

output [
  {
    name: "score"
    data_type: TYPE_FP32
    dims: [ 0, 0, 4233 ]
  },
  {
    name: "r_score"
    data_type: TYPE_FP32
    dims: [ 0, 0, 4233 ]
  }
]

dynamic_batching {
    preferred_batch_size: [ 16, 32 ]
  }

instance_group [
    {
      count: 2
      kind: KIND_CPU
    }
]

