# Copyright (c) 2021 NVIDIA CORPORATION
#               2023 58.com(Wuba) Inc AI Lab.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "scoring"
backend: "python"
max_batch_size: 0

parameters [
  {
    key: "vocabulary"
    value: { string_value: "/ws/onnx_model/words.txt"}
  },
  {
    key: "bidecoder"    # 使用了双向解码器，需要修改model.py
    value: { string_value: "1"}
  },
  {
    key: "lm_path"
    value: { string_value: "None"}
  },
  {
   key: "hotwords_path"
   value : { string_value: "None"}
  }
]
# 这里需要改，现在encoder的输出变成了output:dims[0,0,256],r_att_cache:[12, 4, 0, 128],r_cnn_cache:[12, 1, 256, 0]
input [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [-1, -1, 256]
  },
 
  {
    name: "probs"       
    data_type: TYPE_FP32    # 这里可能是ctc_log_probs,#(batch_size, time_steps, vocab_size) 批次大小、时间步数、字符集大小。
    dims: [-1, -1, 4233]
  }
]
# 最后一步输出的
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [1]
  }
]

dynamic_batching {
    preferred_batch_size: [ 16, 32 ]
  }

instance_group [
    {
      count: 4
      kind: KIND_CPU
    }
  ]
